ESDEV-3861 Use oxUtilsDate to get time not date() to mock in test
Using date() makes testing impossible as test fixture might have different time:
-'OxidEsales\Eshop\Core\Exception\ConnectionException-OxidEsales\Eshop\Core\Exception\StandardException (time: 2016-08-16 16:21:53): [0]: not set
+'OxidEsales\Eshop\Core\Exception\ConnectionException-OxidEsales\Eshop\Core\Exception\StandardException (time: 2016-08-16 16:21:54): [0]: not set

usage of oxTestModules::addFunction("oxUtilsDate"... ) prevents from mock beeing used:
SystemComponentException: Function 'setTime' does not exist or is not accessible!